define([], function () {
    let settingConfig = {
        app: 'rotating_device',
        dialogTitle: '成型旋转线数据配置',
        fields: [
            {"key": "DeviceType", "description": "设备型号"},
            {"key": "DeviceSpec", "description": "设备规格"},
            {"key": "DeviceSize", "description": "机械尺寸"},
            {"key": "ProductFactory", "description": "生产厂家"},
            {"key": "ProductDate", "description": "生产日期"},
            {"key": "ProductCapacity", "description": "产能"},
            {"key": "Outsole1NowValue", "description": "1#大底温度"},
            {"key": "Outsole2NowValue", "description": "2#大底温度"},
            {"key": "Outsole3NowValue", "description": "3#大底温度"},
            {"key": "Vamp1NowValue", "description": "1#鞋面温度"},
            {"key": "Vamp2NowValue", "description": "2#鞋面温度"},
            {"key": "Vamp3NowValue", "description": "3#鞋面温度"},
            {"key": "01_value", "description": "输送带速度"},
            {"key": "02_value", "description": "设备工作电流"},
            {"key": "03_value", "description": "每双用电"},
            {"key": "04_value", "description": "机器故障"},
            {"key": "05_value", "description": "品质问题"},
            {"key": "06_value", "description": "缺料"},
            {"key": "07_value", "description": "其他"},
            {"key": "Outsole1Max", "description": "1#大底温度上限"},
            {"key": "Vamp1Max", "description": "1#鞋面温度上限"},
            {"key": "Outsole2Max", "description": "2#大底温度上限"},
            {"key": "Vamp2Max", "description": "2#鞋面温度上限"},
            {"key": "Outsole3Max", "description": "3#大底温度上限"},
            {"key": "Vamp3Max", "description": "3#鞋面温度上限"},
            {"key": "Outsole1Min", "description": "1#大底温度下限"},
            {"key": "Vamp1Min", "description": "1#鞋面温度下限"},
            {"key": "Outsole2Min", "description": "2#大底温度下限"},
            {"key": "Vamp2Min", "description": "2#鞋面温度下限"},
            {"key": "Outsole3Min", "description": "3#大底温度下限"},
            {"key": "Vamp3Min", "description": "3#鞋面温度下限"},
            {"key": "08_value", "description": "1#大底温度报警"},
            {"key": "09_value", "description": "2#大底温度报警"},
            {"key": "10_value", "description": "3#大底温度报警"},
            {"key": "11_value", "description": "灯管故障报警"},
            {"key": "12_value", "description": "风机故障报警"},
            {"key": "13_value", "description": "1#鞋面温度报警"},
            {"key": "14_value", "description": "2#鞋面温度报警"},
            {"key": "15_value", "description": "3#鞋面温度报警"},
            {"key": "16_value", "description": "输送马达报警"},
            {"key": "TodayGoal", "description": "今日目标"},
            {"key": "17_value", "description": "当前目标"},
            {"key": "18_value", "description": "运行时间"},
            {"key": "19_value", "description": "实际产量"},
            {"key": "20_value", "description": "设备达成率"}
        ]
    };
    return settingConfig;
});