define([], function () {
    let settingConfig = {
        app: 'wall_press_machine_board',
        dialogTitle: '墙式压底机数据配置',
        fields: [{
            key: 'DeviceType',
            description: '设备型号',
            lastKey: 'DeviceType'
        }, {
            key: 'DeviceRateVoltage',
            description: '额定电压',
            lastKey: 'DeviceRateVoltage'
        }, {
            key: 'DeviceRatePressure',
            description: '额定气压',
            lastKey: 'DeviceRatePressure'
        }, {
            key: 'DeviceTotalRunTime',
            description: '运行时间',
            lastKey: 'DeviceTotalRunTime'
        }, {
            key: 'OliPressure',
            description: '额定油压',
            lastKey: 'OliPressure'
        }, {
            key: 'OliTemp',
            description: '油温',
            lastKey: 'OliTemp'
        }, {
            key: 'DeviceRatePower',
            description: '额定功率',
            lastKey: 'DeviceRatePower'
        }, {
            key: 'IPAddress',
            description: 'IP地址',
            lastKey: 'IPAddress'
        }, {
            key: 'ControlSystemVersion',
            description: '控制系统版本',
            lastKey: 'ControlSystemVersion'
        }, {
            key: '3_4505',
            description: '左边压着时间设定值',
            lastKey: '3_4505'
        }, {
            key: '3_4512',
            description: '右边压着时间设定值',
            lastKey: '3_4512'
        }, {
            key: '3_4504',
            description: '左边束紧回程时间设定值',
            lastKey: '3_4504'
        }, {
            key: '3_4511',
            description: '右边束紧回程时间设定值',
            lastKey: '3_4511'
        }, {
            key: '1_2575',
            description: '左边成型后二次加压开关',
            lastKey: '1_2575'
        }, {
            key: '1_2611',
            description: '左边二次压开关状态',
            lastKey: '1_2611'
        }, {
            key: '1_2560',
            description: '左边束紧器开关状态',
            lastKey: '1_2560'
        }, {
            key: '1_2561',
            description: '当前左边操作模式',
            lastKey: '1_2561'
        }, {
            key: '1_2562',
            description: '当前左边加压模式',
            lastKey: '1_2562'
        }, {
            key: '1_2564',
            description: '当前左边加工模式',
            lastKey: '1_2564'
        }, {
            key: '1_2565',
            description: '当前左边加工模式',
            lastKey: '1_2565'
        }, {
            key: '1_2566',
            description: '当前左边加工模式',
            lastKey: '1_2566'
        }, {
            key: '1_2576',
            description: '右边成型后二次加压开关',
            lastKey: '1_2576'
        }, {
            key: '1_2612',
            description: '右边二次压开关状态',
            lastKey: '1_2612'
        }, {
            key: '1_2567',
            description: '右边束紧器开关状态',
            lastKey: '1_2567'
        }, {
            key: '1_2568',
            description: '当前右边操作模式',
            lastKey: '1_2568'
        }, {
            key: '1_2569',
            description: '当前右边加压模式',
            lastKey: '1_2569'
        }, {
            key: '1_2572',
            description: '当前右边加工模式',
            lastKey: '1_2572'
        }, {
            key: '1_2571',
            description: '当前右边加工模式',
            lastKey: '1_2571'
        }, {
            key: '1_2574',
            description: '当前右边加工模式',
            lastKey: '1_2574'
        }, {
            key: '1_1285',
            description: '左束紧进控制状态',
            lastKey: '1_1285'
        }, {
            key: '1_1286',
            description: '左束紧退控制状态',
            lastKey: '1_1286'
        }, {
            key: '1_1287',
            description: '左压边进控制状态',
            lastKey: '1_1287'
        }, {
            key: '1_1288',
            description: '左压边退控制状态',
            lastKey: '1_1288'
        }, {
            key: '1_1281',
            description: '左一次压进控制状态',
            lastKey: '1_1281'
        }, {
            key: '1_1283',
            description: '左二次压进控制状态',
            lastKey: '1_1283'
        }, {
            key: '1_1282',
            description: '左压下降',
            lastKey: '1_1282'
        }, {
            key: '1_1280',
            description: '左压杆平移进控制状态',
            lastKey: '1_1280'
        }, {
            key: '1_1284',
            description: '左压杆平移退控制状态',
            lastKey: '1_1284'
        }, {
            key: '2_1024',
            description: '左启动开关状态',
            lastKey: '2_1024'
        }, {
            key: '2_1025',
            description: '左平移限位状态',
            lastKey: '2_1025'
        }, {
            key: '2_1026',
            description: '左上升限位状态',
            lastKey: '2_1026'
        }, {
            key: '2_1027',
            description: '左下降限位状态',
            lastKey: '2_1027'
        }, {
            key: '2_1028',
            description: '左急退开关状态',
            lastKey: '2_1028'
        }, {
            key: '1_1296',
            description: '右束紧进控制状态',
            lastKey: '1_1296'
        }, {
            key: '1_1297',
            description: '右束紧退控制状态',
            lastKey: '1_1297'
        }, {
            key: '1_1298',
            description: '右压边进控制状态',
            lastKey: '1_1298'
        }, {
            key: '1_1299',
            description: '右压边退控制状态',
            lastKey: '1_1299'
        }, {
            key: '1_1292',
            description: '右一次压进控制状态',
            lastKey: '1_1292'
        }, {
            key: '1_1294',
            description: '右二次压进控制状态',
            lastKey: '1_1294'
        }, {
            key: '1_1293',
            description: '右压下降',
            lastKey: '1_1293'
        }, {
            key: '1_1291',
            description: '右压杆平移进控制状态',
            lastKey: '1_1291'
        }, {
            key: '1_1295',
            description: '右压杆平移退控制状态',
            lastKey: '1_1295'
        }, {
            key: '2_1029',
            description: '右启动开关状态',
            lastKey: '2_1029'
        }, {
            key: '2_1030',
            description: '右平移限位状态',
            lastKey: '2_1030'
        }, {
            key: '2_1031',
            description: '右上升限位状态',
            lastKey: '2_1031'
        }, {
            key: '2_1032',
            description: '右上升限位状态',
            lastKey: '2_1032'
        }, {
            key: '2_1033',
            description: '右急退开关状态',
            lastKey: '2_1033'
        }, {
            key: '3_4532',
            description: '左侧实时产量',
            lastKey: '3_4532'
        }, {
            key: '1_2065',
            description: '左清零',
            lastKey: '1_2065'
        }, {
            key: '3_4534',
            description: '右侧实时产量',
            lastKey: '3_4534'
        }, {
            key: '1_2066',
            description: '右清零',
            lastKey: '1_2066'
        }]
    };
    return settingConfig;
});