define([], function () {
    var bacnetObjectType = [
        {
            name: "analogInput",
            id: 0
        }, {
            name: "analogOutput",
            id: 1
        }, {
            name: "analogValue",
            id: 2
        }, {
            name: "binaryInput",
            id: 3
        }, {
            name: "binaryOutput",
            id: 4
        }, {
            name: "binaryValue",
            id: 5
        }, {
            name: "calendar",
            id: 6
        }, {
            name: "command",
            id: 7
        }, {
            name: "device",
            id: 8
        }, {
            name: "eventEnrollment",
            id: 9
        }, {
            name: "file",
            id: 10
        }, {
            name: "group",
            id: 11
        }, {
            name: "loop",
            id: 12
        }, {
            name: "multiStateInput",
            id: 13
        }, {
            name: "multiStateOutput",
            id: 14
        }, {
            name: "notificationClass",
            id: 15
        }, {
            name: "program",
            id: 16
        }, {
            name: "schedule",
            id: 17
        }, {
            name: "averaging",
            id: 18
        }, {
            name: "multiStateValue",
            id: 19
        }, {
            name: "trendLog",
            id: 20
        }, {
            name: "lifeSafetyPoint",
            id: 21
        }, {
            name: "lifeSafetyZone",
            id: 22
        }, {
            name: "accumulator",
            id: 23
        }, {
            name: "pulseConverter",
            id: 24
        }, {
            name: "eventLog",
            id: 25
        }, {
            name: "globalGroup",
            id: 26
        }, {
            name: "trendLogMultiple",
            id: 27
        }, {
            name: "loadControl",
            id: 28
        }, {
            name: "structuredView",
            id: 29
        }, {
            name: "accessDoor",
            id: 30
        }, {
            name: "timer",
            id: 31
        }, {
            name: "accessCredential",
            id: 32
        }, {
            name: "accessPoint",
            id: 33
        }, {
            name: "accessRights",
            id: 34
        }, {
            name: "accessUser",
            id: 35
        }, {
            name: "accessZone",
            id: 36
        }, {
            name: "credentialDataInput",
            id: 37
        }, {
            name: "networkSecurity",
            id: 38
        }, {
            name: "bitstringValue",
            id: 39
        }, {
            name: "characterstringValue",
            id: 40
        }, {
            name: "datePatternValue",
            id: 41
        }, {
            name: "dateValue",
            id: 42
        }, {
            name: "datetimePatternValue",
            id: 43
        }, {
            name: "datetimeValue",
            id: 44
        }, {
            name: "integerValue",
            id: 45
        }, {
            name: "largeAnalogValue",
            id: 46
        }, {
            name: "octetstringValue",
            id: 47
        }, {
            name: "positiveIntegerValue",
            id: 48
        }, {
            name: "timePatternValue",
            id: 49
        }, {
            name: "timeValue",
            id: 50
        }, {
            name: "notificationForwarder",
            id: 51
        }, {
            name: "alertEnrollment",
            id: 52
        }, {
            name: "channel",
            id: 53
        }, {
            name: "lightingOutput",
            id: 54
        }, {
            name: "binaryLightingOutput",
            id: 55
        }, {
            name: "networkPort",
            id: 56
        }, {
            name: "elevatorGroup",
            id: 57
        }, {
            name: "escalator",
            id: 58
        }, {
            name: "lift",
            id: 59
        }
    ];
    return bacnetObjectType;
});