define([], function () {
    let settingConfig = {
        app: 'wrench_board',
        dialogTitle: '扭力扳手数据配置',
        fields: [{
            key: 'DeviceID',
            description: '扳手ID',
            lastKey: 'MachineID'
        }, {
            key: 'Company',
            description: '公司名称',
            lastKey: 'Company'
        }, {
            key: 'MotorID',
            description: '电机参数ID',
            lastKey: 'MotorID'
        }, {
            key: 'Poles',
            description: '极对数',
            lastKey: 'Poles'
        }, {
            key: 'EncoderLine',
            description: '编码器线数',
            lastKey: 'EncoderLine'
        }, {
            key: 'ReductionRatio',
            description: '减速机减速比',
            lastKey: 'ReductionRatio'
        }, {
            key: 'Power',
            description: '供电电压',
            lastKey: 'Power'
        }, {
            key: 'MaxPhaseCurrent',
            description: '电路板允许最大相电流',
            lastKey: 'MaxPhaseCurrent'
        }, {
            key: 'PhaseResistance',
            description: '相电阻',
            lastKey: 'PhaseResistance'
        }, {
            key: 'PhaseInductance',
            description: '相电感',
            lastKey: 'PhaseInductance'
        }, {
            key: 'NoLoadSpeed',
            description: '电机最高转速',
            lastKey: 'NoLoadSpeed'
        }, {
            key: 'NominalSpeed',
            description: '电机额定转速',
            lastKey: 'NominalSpeed'
        }, {
            key: 'NominalTorque',
            description: '电机额定转矩',
            lastKey: 'NominalTorque'
        }, {
            key: 'NominalCurrent',
            description: '电机额定电流',
            lastKey: 'NominalCurrent'
        }, {
            key: 'CurrentFrequency',
            description: '电流环频率',
            lastKey: 'CurrentFrequency'
        }, {
            key: 'PlanFrequency',
            description: '规划环频率',
            lastKey: 'PlanFrequency'
        }, {
            key: 'CraftID',
            description: '工艺类型ID',
            lastKey: 'CraftID'
        }, {
            key: 'CraftName',
            description: '工艺名称',
            lastKey: 'CraftName'
        }, {
            key: 'SpdUp1',
            description: '一次预拧紧速度',
            lastKey: 'spdUp1'
        }, {
            key: 'Ref_High',
            description: '一次预拧紧目标值',
            lastKey: 'ref_High'
        }, {
            key: 'SpdDn1',
            description: '二次预拧紧减速度',
            lastKey: 'spdDn1'
        }, {
            key: 'Ref_Final1',
            description: '一次拧紧目标值',
            lastKey: 'ref_Final1'
        }, {
            key: 'Keeppoints1',
            description: '一次预拧紧保持点数',
            lastKey: 'keeppoints1'
        }, {
            key: 'SpdDn2',
            description: '反向消应力减速度',
            lastKey: 'spdDn2'
        }, {
            key: 'Ref_Reverse',
            description: '反向消除应力目标值',
            lastKey: 'ref_Reverse'
        }, {
            key: 'Keeppoints4',
            description: '反向走的角度（圈数）',
            lastKey: 'keeppoints4'
        }, {
            key: 'SpdUp2',
            description: '二次拧紧加速度',
            lastKey: 'spdUp2'
        }, {
            key: 'Ref_Final2',
            description: '二次拧紧目标值',
            lastKey: 'ref_Final2'
        }, {
            key: 'Keeppoints2',
            description: '二次拧紧保持点数',
            lastKey: 'keeppoints2'
        }, {
            key: 'SpdDn3',
            description: '退出减速度',
            lastKey: 'spdDn3'
        }, {
            key: 'Keeppoints3',
            description: '退出保持点数',
            lastKey: 'keeppoints3'
        }]
    };
    return settingConfig;
});