define([], function () {
    var keyboard = [{
        'key': 'Up',
        'keyCode': 65362
    }, {
        'key': 'Down',
        'keyCode': 65364
    }, {
        'key': 'Left',
        'keyCode': 65361
    }, {
        'key': 'Right',
        'keyCode': 65363
    }, {
        'key': 'F4',
        'keyCode': 65473
    }, {
        'key': 'F5',
        'keyCode': 65474
    }, {
        'key': 'H',
        'keyCode': 104
    }, {
        'key': 'R',
        'keyCode': 114
    }, {
        'key': 'Ctrl',
        'keyCode': 65508
    }, {
        'key': 'C',
        'keyCode': 99
    }, {
        'key': 'G',
        'keyCode': 103
    }, {
        'key': '7',
        'keyCode': 55
    }, {
        'key': '8',
        'keyCode': 56
    }, {
        'key': '9',
        'keyCode': 57
    }, {
        'key': '4',
        'keyCode': 52
    }, {
        'key': '5',
        'keyCode': 53
    }, {
        'key': '6',
        'keyCode': 54
    }, {
        'key': '1',
        'keyCode': 49
    }, {
        'key': '2',
        'keyCode': 50
    }, {
        'key': '3',
        'keyCode': 51
    }, {
        'key': '0',
        'keyCode': 48
    }, {
        'key': '.',
        'keyCode': 46
    }, {
        'key': '-',
        'keyCode': 45
    }, {
        'key': 'Backspace',
        'keyCode': 65288
    }, {
        'key': 'Enter',
        'keyCode': 65421
    }, {
        'key': 'F8',
        'keyCode': 65477
    }, {
        'key': 'F9',
        'keyCode': 65478
    }, {
        'key': 'L',
        'keyCode': 108
    }, {
        'key': 'F7',
        'keyCode': 65476
    }, {
        'key': 'E',
        'keyCode': 101
    }, {
        'key': 'B',
        'keyCode': 98
    }, {
        'key': 'T',
        'keyCode': 116
    }, {
        'key': 'D',
        'keyCode': 100
    }, {
        'key': 'Y',
        'keyCode': 121
    }, {
        'key': 'Shift',
        'keyCode': 65506
    }, {
        'key': 'Q',
        'keyCode': 113
    }, {
        'key': 'W',
        'keyCode': 119
    }, {
        'key': 'A',
        'keyCode': 97
    }, {
        'key': 'S',
        'keyCode': 115
    }, {
        'key': 'Z',
        'keyCode': 122
    }, {
        'key': 'X',
        'keyCode': 120
    }, {
        'key': 'U',
        'keyCode': 117
    }, {
        'key': 'I',
        'keyCode': 105
    }, {
        'key': 'J',
        'keyCode': 106
    }, {
        'key': 'K',
        'keyCode': 107
    }, {
        'key': 'N',
        'keyCode': 110
    }, {
        'key': 'M',
        'keyCode': 109
    }, {
        'key': 'O',
        'keyCode': 111
    }, {
        'key': 'P',
        'keyCode': 112
    }, {
        'key': 'F3',
        'keyCode': 65472
    }, {
        'key': 'F2',
        'keyCode': 65471
    }, {
        'key': 'Windows',
        'keyCode': 65515
    }, {
        'key': 'Alt',
        'keyCode': 65513
    }, {
        'key': 'Delete',
        'keyCode': 0xFFFF
    }];
    return keyboard;
});