define([], function () {
    let settingConfig = {
        app: 'rear_setting_machine_board_v2',
        dialogTitle: '后踵定型机（两冷两热）数据配置',
        fields: [{
            description: '工号',
            key: "EmpNO"
        }, {
            key: 'DeviceType',
            description: '型号',
            lastKey: 'DeviceType'
        }, {
            key: 'DeviceRateVoltag',
            description: '额定电压',
            lastKey: 'DeviceRateVoltag'
        }, {
            key: 'CmsPressHigh',
            description: '总气压值',
            lastKey: 'CmsPressHigh'
        }, {
            key: 'DeviceRatePressure',
            description: '额定气压',
            lastKey: 'DeviceRatePressure'
        }, {
            key: 'DeviceRatePowe',
            description: '额定功率',
            lastKey: 'DeviceRatePowe'
        }, {
            key: 'IPAdress',
            description: 'IP地址',
            lastKey: 'IPAdress'
        }, {
            key: 'ConrolSystemVersion',
            description: '控制系统版本',
            lastKey: 'ConrolSystemVersion'
        }, {
            key: 'Production',
            description: '加工产品',
            lastKey: 'Production'
        }, {
            key: 'WorkSts',
            description: '工作状态',
            lastKey: 'WorkSts'
        }, {
            key: 'DeviceTotalRunTime',
            description: '总运行时间',
            lastKey: 'DeviceTotalRunTime'
        }, {
            key: 'DeviceCurRunTime',
            description: '单次开机运行时间',
            lastKey: 'DeviceCurRunTime'
        }, {
            key: 'LeftPlanProduction',
            description: '左侧计划产量',
            lastKey: 'LeftPlanProduction'
        }, {
            key: 'LeftFinishProduction',
            description: '左侧完成产量',
            lastKey: 'LeftFinishProduction'
        }, {
            key: 'RightPlanProduction',
            description: '右侧计划产量',
            lastKey: 'RightPlanProduction'
        }, {
            key: 'RightFinishProduction',
            description: '右侧完成产量',
            lastKey: 'RightFinishProduction'
        }, {
            key: 'DeviceAlarm',
            description: '设备报警信息',
            lastKey: 'DeviceAlarm'
        }, {
            key: '1_2058',
            description: '左热模气缸状态',
            lastKey: '1_2058'
        }, {
            key: '1_2059',
            description: '右热模气缸状态',
            lastKey: '1_2059'
        }, {
            key: '1_1302',
            description: '左冷模气缸状态',
            lastKey: '1_1302'
        }, {
            key: '1_1312',
            description: '右冷模气缸状态',
            lastKey: '1_1312'
        }, {
            key: '1_2168',
            description: '演示开关',
            lastKey: '1_2168'
        }, {
            key: '1_2170',
            description: '摆头后摇开关',
            lastKey: '1_2170'
        }, {
            key: '1_2148',
            description: '扫刀选择开关',
            lastKey: '1_2148'
        }, {
            key: '1_2169',
            description: '手动扫刀开关',
            lastKey: '1_2169'
        }, {
            key: '1_2581',
            description: '夹爪选择开关',
            lastKey: '1_2581'
        }, {
            key: '2_1024',
            description: '左热模脚踏开关',
            lastKey: '2_1024'
        }, {
            key: '2_1025',
            description: '左热模启动按钮',
            lastKey: '2_1025'
        }, {
            key: '2_1026',
            description: '左热模行程开关',
            lastKey: '2_1026'
        }, {
            key: '2_1027',
            description: '左热模紧急开关',
            lastKey: '2_1027'
        }, {
            key: '2_1028',
            description: '右热模脚踏开关',
            lastKey: '2_1028'
        }, {
            key: '2_1029',
            description: '右热模启动按钮',
            lastKey: '2_1029'
        }, {
            key: '2_1030',
            description: '右热模行程开关',
            lastKey: '2_1030'
        }, {
            key: '2_1031',
            description: '右热模紧急开关',
            lastKey: '2_1031'
        }, {
            key: '2_1044',
            description: '左冷模脚踏开关',
            lastKey: '2_1044'
        }, {
            key: '2_1045',
            description: '左冷/热模启动按钮',
            lastKey: '2_1045'
        }, {
            key: '2_1046',
            description: '左/右冷模启动按钮',
            lastKey: '2_1046'
        }, {
            key: '2_1047',
            description: '左冷模摆头行程开关',
            lastKey: '2_1047'
        }, {
            key: '2_1048',
            description: '左冷模下压行程开关',
            lastKey: '2_1048'
        }, {
            key: '2_1049',
            description: '左冷模紧急开关',
            lastKey: '2_1049'
        }, {
            key: '2_1054',
            description: '右冷模脚踏开关',
            lastKey: '2_1054'
        }, {
            key: '2_1055',
            description: '右冷/热模启动按钮',
            lastKey: '2_1055'
        }, {
            key: '2_1056',
            description: '右热模摆头行程开关',
            lastKey: '2_1056'
        }, {
            key: '2_1057',
            description: '右冷模下压行程开关',
            lastKey: '2_1057'
        }, {
            key: '2_1058',
            description: '右冷模紧急开关',
            lastKey: '2_1058'
        }, {
            key: '1_1280',
            description: '左热模夹爪动作',
            lastKey: '1_1280'
        }, {
            key: '1_1281',
            description: '左热模下压',
            lastKey: '1_1281'
        }, {
            key: '1_1282',
            description: '右热模夹爪动作',
            lastKey: '1_1282'
        }, {
            key: '1_1283',
            description: '右热模下压',
            lastKey: '1_1283'
        }, {
            key: '1_1300',
            description: '左冷模夹爪动作',
            lastKey: '1_1300'
        }, {
            key: '1_1301',
            description: '左冷模摆头',
            lastKey: '1_1301'
        }, {
            key: '1_1302',
            description: '左冷模下压',
            lastKey: '1_1302'
        }, {
            key: '1_1303',
            description: '左冷模扫刀',
            lastKey: '1_1303'
        }, {
            key: '1_1310',
            description: '右冷模夹爪动作',
            lastKey: '1_1310'
        }, {
            key: '1_1311',
            description: '右冷模摆头',
            lastKey: '1_1311'
        }, {
            key: '1_1312',
            description: '右冷模下压',
            lastKey: '1_1312'
        }, {
            key: '1_1313',
            description: '右冷模扫刀',
            lastKey: '1_1313'
        }, {
            key: '3_4596',
            description: '热模压着时间设定',
            lastKey: '3_4596'
        }, {
            key: '3_4600',
            description: '冷模压着时间设定',
            lastKey: '3_4600'
        }, {
            key: '3_4606',
            description: '扫刀时间设定',
            lastKey: '3_4606'
        }, {
            key: '3_4607',
            description: '热模夹爪延时设定',
            lastKey: '3_4607'
        }, {
            key: '3_4601',
            description: '摆头延时设定',
            lastKey: '3_4601'
        }, {
            key: '3_4598',
            description: '冷模扫刀延时设定',
            lastKey: '3_4598'
        }, {
            key: '3_4597',
            description: '冷模下压延时设定',
            lastKey: '3_4597'
        }, {
            key: '3_4706',
            description: '冷模设定温度',
            lastKey: '3_4706'
        }, {
            key: '3_4707',
            description: '左上热模设定温度',
            lastKey: '3_4707'
        }, {
            key: '3_4708',
            description: '左下热模设定温度',
            lastKey: '3_4708'
        }, {
            key: '3_4709',
            description: '右上热模设定温度',
            lastKey: '3_4709'
        }, {
            key: '3_4710',
            description: '右下热模设定温度',
            lastKey: '3_4710'
        }, {
            key: '3_4696',
            description: '冷模实际温度',
            lastKey: '3_4696'
        }, {
            key: '3_4697',
            description: '左上热模实际温度',
            lastKey: '3_4697'
        }, {
            key: '3_4698',
            description: '左下热模实际温度',
            lastKey: '3_4698'
        }, {
            key: '3_4699',
            description: '右上热模实际温度',
            lastKey: '3_4699'
        }, {
            key: '3_4700',
            description: '右下热模实际温度',
            lastKey: '3_4700'
        }, {
            key: '3_1536',
            description: '左热模压着时间当前值',
            lastKey: '3_1536'
        }, {
            key: '3_1537',
            description: '右热模压着时间当前值',
            lastKey: '3_1537'
        }, {
            key: '3_1549',
            description: '左冷模压着时间当前值',
            lastKey: '3_1549'
        }, {
            key: '3_1559',
            description: '右冷模压着时间当前值',
            lastKey: '3_1559'
        }, {
            key: '3_4628',
            description: '工作时长',
            lastKey: '3_4628'
        }, {
            key: '3_4509',
            description: '实时产量（双）',
            lastKey: '3_4509'
        }, {
            key: '3_4531',
            description: '良品数',
            lastKey: '3_4531'
        }, {
            key: '3_4527',
            description: '次品数',
            lastKey: '3_4527'
        }, {
            key: '3_4536',
            description: '良品率',
            lastKey: '3_4536'
        },
        ]
    };
    return settingConfig;
});