define([], function () {
    let settingConfig = {
        app: 'rear_setting_machine_board',
        dialogTitle: '后踵定型机（两冷四热）数据配置',
        fields: [ {
            description: '工号',
            key: "EmpNO"
        },{
            key: 'DeviceType',
            description: '型号',
            lastKey: 'DeviceType'
        }, {
            key: 'DeviceRateVoltag',
            description: '额定电压',
            lastKey: 'DeviceRateVoltag'
        }, {
            key: 'DeviceRatePressure',
            description: '额定气压',
            lastKey: 'DeviceRatePressure'
        }, {
            key: 'DeviceRatePowe',
            description: '额定功率',
            lastKey: 'DeviceRatePowe'
        }, {
            key: 'IPAdress',
            description: 'IP地址',
            lastKey: 'IPAdress'
        }, {
            key: 'ConrolSystemVersion',
            description: '控制系统版本',
            lastKey: 'ConrolSystemVersion'
        }, {
            key: 'Production',
            description: '加工产品',
            lastKey: 'Production'
        }, {
            key: 'WorkSts',
            description: '工作状态',
            lastKey: 'WorkSts'
        }, {
            key: 'DeviceTotalRunTime',
            description: '总运行时间',
            lastKey: 'DeviceTotalRunTime'
        }, {
            key: 'DeviceCurRunTime',
            description: '单次开机运行时间',
            lastKey: 'DeviceCurRunTime'
        }, {
            key: 'LeftPlanProduction',
            description: '左侧计划产量',
            lastKey: 'LeftPlanProduction'
        }, {
            key: 'LeftFinishProduction',
            description: '左侧完成产量',
            lastKey: 'LeftFinishProduction'
        }, {
            key: 'RightPlanProduction',
            description: '右侧计划产量',
            lastKey: 'RightPlanProduction'
        }, {
            key: 'RightFinishProduction',
            description: '右侧完成产量',
            lastKey: 'RightFinishProduction'
        }, {
            key: 'DeviceAlarm',
            description: '设备报警信息',
            lastKey: 'DeviceAlarm'
        }, {
            description: '左侧热风工位时间设定值',
            key: "LeftHotAirStationLoop"
        }, {
            description: '左侧热风工位时间当前值',
            key: "LeftCurTmieHotAirSta"
        }, {
            description: '右侧热风工位时间设定值',
            key: "RightHotAirStationLoop"
        }, {
            description: '右侧热风工位时间当前值',
            key: "RightCurTmieHotAirSta"
        }, {
            description: '左侧铝热工位充气时间设定值',
            key: "LahAirbagInflatingLoop"
        }, {
            description: '左侧铝热工位充气时间当前值',
            key: "LahCurTimeInflating"
        }, {
            description: '左侧铝热工位放气时间设定值',
            key: "LahAirbagExhaustLoop"
        }, {
            description: '左侧铝热工位放气时间当前值',
            key: "LahCurTimeExhaust"
        }, {
            description: '右侧铝热工位充气时间设定值',
            key: "RahAirbagInflatingLoop"
        }, {
            description: '右侧铝热工位充气时间当前值',
            key: "RahCurTimeInflating"
        }, {
            description: '右侧铝热工位放气时间设定值',
            key: "RahAirbagExhaustLoop"
        }, {
            description: '右侧铝热工位放气时间当前值',
            key: "RahCurTimeExhaust"
        }, {
            description: '左侧铝冷工位充气时间设定值',
            key: "LacAirbagInflatingLoop"
        }, {
            description: '左侧铝冷工位充气时间当前值',
            key: "LacCurTimeInflating"
        }, {
            description: '左侧铝冷工位放气时间设定值',
            key: "LacAirbagExhaustLoop"
        }, {
            description: '左侧铝冷工位放气时间当前值',
            key: "LacCurTimeExhaust"
        }, {
            description: '右侧铝冷工位充气时间设定值',
            key: "RacAirbagInflatingLoop"
        }, {
            description: '右侧铝冷工位充气时间当前值',
            key: "RacCurTimeInflating"
        }, {
            description: '右侧铝冷工位放气时间设定值',
            key: "RacAirbagExhaustLoop"
        }, {
            description: '右侧铝冷工位放气时间当前值',
            key: "RacCurTimeExhaust"
        }, {
            description: '右侧铝冷工位温度设定值',
            key: "RacTempSet"
        }, {
            description: '右侧铝冷工位温度当前值',
            key: "RacTempCur"
        }, {
            description: '左侧热风工位温度设定值',
            key: "LhaTempSet"
        }, {
            description: '左侧热风工位温度当前值',
            key: "LhaTempCur"
        }, {
            description: '右侧热风工位温度设定值',
            key: "RhaTempSet"
        }, {
            description: '右侧热风工位温度当前值',
            key: "RhaTempCur"
        }, {
            description: '左侧铝热工位温度设定值',
            key: "LahTempSet"
        }, {
            description: '左侧铝热工位温度当前值',
            key: "LahTempCur"
        }, {
            description: '右侧铝热工位温度设定值',
            key: "RahTempSet"
        }, {
            description: '右侧铝热工位温度当前值',
            key: "RahTempCur"
        }, {
            description: '左侧铝冷工位温度设定值',
            key: "LacTempSet"
        }, {
            description: '左侧铝冷工位温度当前值',
            key: "LacTempCur"
        }, {
            description: '电热管1工作状态(正常或报警)',
            key: "ElectHeatTubeSts1"
        }, {
            description: '电热管2工作状态(正常或报警)',
            key: "ElectHeatTubeSts2"
        }, {
            description: '电热管3工作状态(正常或报警)',
            key: "ElectHeatTubeSts3"
        }, {
            description: '电热管4工作状态(正常或报警)',
            key: "ElectHeatTubeSts4"
        }, {
            description: '气路1压力工作状态',
            key: "GasPressureSts1"
        }, {
            description: '气路2压力工作状态',
            key: "GasPressureSts2"
        }, {
            description: '气路3压力工作状态',
            key: "GasPressureSts3"
        }, {
            description: '气路4压力工作状态',
            key: "GasPressureSts4"
        }, {
            description: '气路5压力工作状态',
            key: "GasPressureSts5"
        }, {
            description: '气路6压力工作状态',
            key: "GasPressureSts6"
        }, {
            description: '气路7压力工作状态',
            key: "GasPressureSts7"
        }, {
            description: '气路8压力工作状态',
            key: "GasPressureSts8"
        }, {
            description: '压缩机工作电流',
            key: "CmsCurrent"
        }, {
            description: '压缩机外壳温度',
            key: "CmsShellTemp"
        }, {
            description: '压缩机高压值',
            key: "CmsPressHigh"
        }, {
            description: '压缩机低压值',
            key: "CmsPressLow"
        }, {
            description: '散热扇工作电流',
            key: "FanCurrent"
        }, {
            description: '散热扇工作风力',
            key: "FanWindPow"
        }, {
            description: '设备噪音值',
            key: "DeviceNoise"
        }, {
            description: '本地DI信号',
            key: "LocalDI"
        }, {
            description: '扩展DI信号',
            key: "ExtendDI"
        }, {
            description: '本地DO信号',
            key: "LocalDO"
        }, {
            description: '扩展DO信号',
            key: "ExtendDO"
        }]
    };
    return settingConfig;
});