define([],function () {
    let settingConfig={
        app: 'robot',
        dialogTitle:'机器人数据配置',
        fields: [{
            key: '004_UserName',
            description: '用户名',
            lastKey: '004_UserName'
        }, {
            key: '012_FactoryName',
            description: '工厂名字',
            lastKey: '012_FactoryName'
        }, {
            key: '013_LineName',
            description: '生产线名字',
            lastKey: '013_LineName'
        }, {
            key: '014_LocationName',
            description: '工位名字',
            lastKey: '014_LocationName'
        }, {
            key: '011_MachineCode',
            description: '机器码',
            lastKey: '011_MachineCode'
        }, {
            key: '009_UserCodeDefault',
            description: 'User code前三段',
            lastKey: '009_UserCodeDefault'
        }, {
            key: '010_UserCodeAddtion',
            description: 'User code后一段',
            lastKey: '010_UserCodeAddtion'
        }, {
            key: '005_IPAddress1',
            description: 'IP地址1',
            lastKey: '005_IPAddress1'
        }, {
            key: '006_IPAddress2',
            description: 'IP地址2',
            lastKey: '006_IPAddress2'
        }, {
            key: '007_MACAddress1',
            description: 'MAC地址1',
            lastKey: '007_MACAddress1'
        }, {
            key: '008_MACAddress2',
            description: 'MAC地址2',
            lastKey: '008_MACAddress2'
        }, {
            key: '003_Axis1ProfilePosition',
            description: 'Axis1规划位置',
            lastKey: '003_Axis1ProfilePosition'
        }, {
            key: '004_Axis2ProfilePosition',
            description: 'Axis2规划位置',
            lastKey: '004_Axis2ProfilePosition'
        }, {
            key: '005_Axis3ProfilePosition',
            description: 'Axis3规划位置',
            lastKey: '005_Axis3ProfilePosition'
        }, {
            key: '006_Axis4ProfilePosition',
            description: 'Axis4规划位置',
            lastKey: '006_Axis4ProfilePosition'
        }, {
            key: '007_Axis5ProfilePosition',
            description: 'Axis5规划位置',
            lastKey: '007_Axis5ProfilePosition'
        }, {
            key: '008_Axis6ProfilePosition',
            description: 'Axis6规划位置',
            lastKey: '008_Axis6ProfilePosition'
        }, {
            key: '009_Axis7ProfilePosition',
            description: 'Axis7规划位置',
            lastKey: '009_Axis7ProfilePosition'
        }, {
            key: '010_Axis8ProfilePosition',
            description: 'Axis8规划位置',
            lastKey: '010_Axis8ProfilePosition'
        }, {
            key: '019_Axis1ProfileVelocity',
            description: 'Axis1 规划速度',
            lastKey: '019_Axis1ProfileVelocity'
        }, {
            key: '020_Axis2ProfileVelocity',
            description: 'Axis2 规划速度',
            lastKey: '020_Axis2ProfileVelocity'
        }, {
            key: '021_Axis3ProfileVelocity',
            description: 'Axis3 规划速度',
            lastKey: '021_Axis3ProfileVelocity'
        }, {
            key: '022_Axis4ProfileVelocity',
            description: 'Axis4 规划速度',
            lastKey: '022_Axis4ProfileVelocity'
        }, {
            key: '023_Axis5ProfileVelocity',
            description: 'Axis5 规划速度',
            lastKey: '023_Axis5ProfileVelocity'
        }, {
            key: '024_Axis6ProfileVelocity',
            description: 'Axis6 规划速度',
            lastKey: '024_Axis6ProfileVelocity'
        }, {
            key: '025_Axis7ProfileVelocity',
            description: 'Axis7 规划速度',
            lastKey: '025_Axis7ProfileVelocity'
        }, {
            key: '026_Axis8ProfileVelocity',
            description: 'Axis8 规划速度',
            lastKey: '026_Axis8ProfileVelocity'
        }, {
            key: '014_CartesianAPosition',
            description: '笛卡尔坐标系A位置',
            lastKey: '014_CartesianAPosition'
        }, {
            key: '015_CartesianBPosition',
            description: '笛卡尔坐标系B位置',
            lastKey: '015_CartesianBPosition'
        }, {
            key: '016_CartesianCPosition',
            description: '笛卡尔坐标系C位置',
            lastKey: '016_CartesianCPosition'
        }, {
            key: '011_CartesianXPosition',
            description: '笛卡尔坐标系X位置',
            lastKey: '011_CartesianXPosition'
        }, {
            key: '012_CartesianYPosition',
            description: '笛卡尔坐标系Y位置',
            lastKey: '012_CartesianYPosition'
        }, {
            key: '013_CartesianZPosition',
            description: '笛卡尔坐标系Z位置',
            lastKey: '013_CartesianZPosition'
        }, {
            key: '027_Motor1Speed',
            description: 'Motor1转速',
            lastKey: '027_Motor1Speed'
        }, {
            key: '028_Motor2Speed',
            description: 'Motor2转速',
            lastKey: '028_Motor2Speed'
        }, {
            key: '029_Motor3Speed',
            description: 'Motor3转速',
            lastKey: '029_Motor3Speed'
        }, {
            key: '030_Motor4Speed',
            description: 'Motor4转速',
            lastKey: '030_Motor4Speed'
        }, {
            key: '031_Motor5Speed',
            description: 'Motor5转速',
            lastKey: '031_Motor5Speed'
        }, {
            key: '032_Motor6Speed',
            description: 'Motor6转速',
            lastKey: '032_Motor6Speed'
        }, {
            key: '033_Motor7Speed',
            description: 'Motor7转速',
            lastKey: '033_Motor7Speed'
        }, {
            key: '034_Motor8Speed',
            description: 'Motor8转速',
            lastKey: '034_Motor8Speed'
        }]
    };
    return settingConfig;
});