define([], function () {
    let settingConfig = {
        app: 'moduleline_device',
        dialogTitle: '模组线机头数据配置',
        fields: [
            // {"key": "DeviceType", "description": "设备型号"},
            // {"key": "DeviceSpec", "description": "设备规格"},
            // {"key": "DeviceSize", "description": "设备尺寸"},
            // {"key": "DeviceRatedVoltage", "description": "设备额定电压"},
            // {"key": "DeviceRatedAirPressure", "description": "设备额定气压"},
            // {"key": "DeviceRatedPower", "description": "设备额定功率"},
            // {"key": "ProcessedProduct", "description": "加工产品"},
            // {"key": "ProductFactory", "description": "生产厂家"},
            {"key": "EnergyUsed", "description": "用电量"},
            {"key": "WarningStop", "description": "故障停线"},
            {"key": "MaterialLessStop", "description": "欠料停线"},
            {"key": "QualityStop", "description": "品质停线"},

            {"key": "3_4397", "description": "药-上层产品温度"},
            {"key": "3_4396", "description": "药-下层产品温度"},
            {"key": "3_4401", "description": "药-上层灯管温度"},
            {"key": "3_4400", "description": "药-下层灯管温度"},
            {"key": "3_4399", "description": "药-上层发热管温度"},
            {"key": "3_4398", "description": "药-下层发热管温度 "},
            {"key": "PotionUpLamp", "description": "药-上层灯管工作电流"},
            {"key": "PotionLowLamp", "description": "药-下层灯管工作电流"},
            {"key": "PotionUpHeater", "description": "药-上层电热管工作电流"},
            {"key": "PotionLowHeater", "description": "药-下层电热管工作电流"},
            {"key": "PotionUpFan", "description": "药-上层烘箱涡流风机工作电流"},
            {"key": "PotionLowFan", "description": "药-下层烘箱涡流风机工作电流"},
            {"key": "PotionInMOT", "description": "药-进板马达工作电流"},
            {"key": "PotionPushMOT", "description": "药-推板马达工作电流"},
            {"key": "PotionOutMOT", "description": "药-出板马达工作电流"},

            {"key": "3_4437", "description": "胶上层产品温度"},
            {"key": "3_4436", "description": "胶-下层产品温度"},
            {"key": "3_4441", "description": "胶-上层灯管温度"},
            {"key": "3_4440", "description": "胶-下层灯管温度"},
            {"key": "3_4439", "description": "胶-上层发热管温度"},
            {"key": "3_4438", "description": "胶-下层发热管温度"},
            {"key": "GlueUpLamp", "description": "胶-上层灯管工作电流"},
            {"key": "GlueLowLamp", "description": "胶-下层灯管工作电流"},
            {"key": "GlueUpHeater", "description": "胶-上层电热管工作电流"},
            {"key": "GlueLowHeater", "description": "胶-下层电热管工作电流"},
            {"key": "GlueUpFan", "description": "胶-上层烘箱涡流风机工作电流"},
            {"key": "GlueLowFan", "description": "胶-下层烘箱涡流风机工作电流"},
            {"key": "GlueInMOT", "description": "胶-进板马达工作电流"},
            {"key": "GluePushMOT", "description": "胶-推板马达工作电流"},
            {"key": "GlueOutMOT", "description": "胶-出板马达工作电流"},
            {"key": "CurTransferSpeed", "description": "胶-当前传送线速度"},
            {"key": "TransferMOT", "description": "胶-输送线马达电流"},
            {"key": "FastLineMOT", "description": "胶-快速线马达电流"},

            {"key": "3_4405", "description": "药-上层灯管温度设定值"},
            {"key": "3_4404", "description": "药-下层灯管温度设定值"},
            {"key": "3_4403", "description": "药-上层发热管温度设定值"},
            {"key": "3_4402", "description": "药-下层发热管温度设定值"},

            {"key": "3_4445", "description": "胶-上层灯管温度设定值"},
            {"key": "3_4444", "description": "胶-下层灯管温度设定值"},
            {"key": "3_4443", "description": "胶-上层发热管温度设定值"},
            {"key": "3_4442", "description": "胶-下层发热管温度设定值"},

            // {"key": "PlanOutput", "description": "计划产量"},
            {"key": "1_2149", "description": "产量"},
            {"key": "PassingNum", "description": "合格数"},
            {"key": "RejectedNum", "description": "次品数"},
            {"key": "RateOfQuality", "description": "良品率"},
            {"key": "OperatingHours", "description": "工作时间（或时长）"},
        ]
    };
    return settingConfig;
});