define([], function () {
    let settingConfig = {
        app: 'press_board',
        dialogTitle: '压机数据配置',
        fields: [{
            key: 'TCP_strUserName',
            description: '用户名',
            lastKey: 'TCP_strUserName'
        }, {
            key: 'TCP_strFactoryName',
            description: '工厂名字',
            lastKey: 'TCP_strFactoryName'
        }, {
            key: 'TCP_strLineName',
            description: '生产线名字',
            lastKey: 'TCP_strLineName'
        }, {
            key: 'TCP_strJobName',
            description: '工位名字',
            lastKey: 'TCP_strJobName'
        }, {
            key: 'TCP_strMachineCode',
            description: '机器码',
            lastKey: 'TCP_strMachineCode'
        }, {
            key: 'TCP_decelerationratio',
            description: '减速比',
            lastKey: 'TCP_decelerationratio'
        }, {
            key: 'TCP_strServerIP1',
            description: 'IP地址',
            lastKey: 'TCP_strServerIP1'
        }, {
            key: 'TCP_strServerIP2',
            description: 'IP地址2',
            lastKey: 'TCP_strServerIP2'
        }, {
            key: 'TCP_MacAddress1',
            description: 'MAC地址1',
            lastKey: 'TCP_MacAddress1'
        }, {
            key: 'TCP_MacAddress2',
            description: 'MAC地址2',
            lastKey: 'TCP_MacAddress2'
        }, {
            key: 'PMP_iPushOverNum',
            description: '当前压装的次数',
            lastKey: 'PMP_iPushOverNum'
        }, {
            key: 'iPushOverNum',
            description: '压装总数',
            lastKey: 'iPushOverNum'
        }, {
            key: 'iControlMode',
            description: '模式选择',
            lastKey: 'iControlMode'
        }, {
            key: 'rSetPushmountingPos',
            description: '目标位置',
            lastKey: 'rSetPushmountingPos'
        }, {
            key: 'rSetPushmountingPre',
            description: '目标压力',
            lastKey: 'rSetPushmountingPre'
        }, {
            key: 'bRelativePreMode',
            description: '相对压力',
            lastKey: 'bRelativePreMode'
        }, {
            key: 'rSetPushmountingRelativePre',
            description: '相对压力值',
            lastKey: 'rSetPushmountingRelativePre'
        }, {
            key: 'bRelativePosAlarmBack',
            description: '位置保护(启动按钮)',
            lastKey: 'bRelativePosAlarmBack'
        }, {
            key: 'rRelativePressCrossPos',
            description: '位置保护(参数值)',
            lastKey: 'rRelativePressCrossPos'
        }, {
            key: 'bRelativeDisAlarmBack',
            description: '位移保护(启动按钮)',
            lastKey: 'bRelativeDisAlarmBack'
        }, {
            key: 'rRelativeBandPressRange',
            description: '位移保护(参数值)',
            lastKey: 'rRelativeBandPressRange'
        }, {
            key: 'bBackPosAlarmBack',
            description: '位置保护(启动按钮)',
            lastKey: 'bBackPosAlarmBack'
        }, {
            key: 'rBackPressCrossPos',
            description: '位置保护(参数值)',
            lastKey: 'rBackPressCrossPos'
        }, {
            key: 'bBackDisAlarmBack',
            description: '位移保护(启动按钮)',
            lastKey: 'bBackDisAlarmBack'
        }, {
            key: 'rBackBandPressRange',
            description: '位移保护(参数值)',
            lastKey: 'rBackBandPressRange'
        }, {
            key: 'rSetPushmountingDis',
            description: '目标位移',
            lastKey: 'rSetPushmountingDis'
        }, {
            key: 'iBackControlMode',
            description: '回退模式',
            lastKey: 'iBackControlMode'
        }, {
            key: 'rBackPreStopLimt',
            description: '压力保护',
            lastKey: 'rBackPreStopLimt'
        }, {
            key: 'rSetStartPos',
            description: '回退位置',
            lastKey: 'rSetStartPos'
        }, {
            key: 'rSetProbePos',
            description: '探测位置',
            lastKey: 'rSetProbePos'
        }, {
            key: 'rSlowDownPoint',
            description: '预压位置',
            lastKey: 'rSlowDownPoint'
        }, {
            key: 'rTotalPushMountingTime',
            description: '保压时间',
            lastKey: 'rTotalPushMountingTime'
        }, {
            key: 'rMinHoldPre',
            description: '保压最小值',
            lastKey: 'rMinHoldPre'
        }, {
            key: 'rMaxHoldPre',
            description: '保压最大值',
            lastKey: 'rMaxHoldPre'
        }, {
            key: 'rAverageHoldPre',
            description: '保压平均值',
            lastKey: 'rAverageHoldPre'
        }, {
            key: 'rSetMaxStroke',
            description: '最大位移',
            lastKey: 'rSetMaxStroke'
        }, {
            key: 'rSetFastForwardVel',
            description: '快进速度',
            lastKey: 'rSetFastForwardVel'
        }, {
            key: 'rSetFastForwardToProbePos',
            description: '快进转探测位置',
            lastKey: 'rSetFastForwardToProbePos'
        }, {
            key: 'bSetPrePushEnablel',
            description: '预压是否启用',
            lastKey: 'bSetPrePushEnablel'
        }, {
            key: 'bPreAlarmBack',
            description: '预压压力保护是否生效',
            lastKey: 'bPreAlarmBack'
        }, {
            key: 'bSetHoldPreEnable',
            description: '保压压力模式启用按钮',
            lastKey: 'bSetHoldPreEnable'
        }, {
            key: 'rSetHoldPre',
            description: '保压压力设定值',
            lastKey: 'rSetHoldPre'
        }, {
            key: 'rSetBackhaulPre',
            description: '反拉拉力',
            lastKey: 'rSetBackhaulPre'
        }, {
            key: 'bBackPreAlarmBack',
            description: '保压压力保护是否生效',
            lastKey: 'bBackPreAlarmBack'
        }, {
            key: 'rSetProbeVel',
            description: '探测速度',
            lastKey: 'rSetProbeVel'
        }, {
            key: 'rSetPrePushVel',
            description: '预压速度',
            lastKey: 'rSetPrePushVel'
        }, {
            key: 'rPrePushPos',
            description: '预压位置',
            lastKey: 'rPrePushPos'
        }, {
            key: 'rSetPushmountingVel',
            description: '压装速度',
            lastKey: 'rSetPushmountingVel'
        }, {
            key: 'rSetBackhaulVel',
            description: '回程速度',
            lastKey: 'rSetBackhaulVel'
        }, {
            key: 'strLogTime',
            description: '日志时间',
            lastKey: 'strLogTime'
        }, {
            key: 'iLogDetails',
            description: '日志内容',
            lastKey: 'iLogDetails'
        }, {
            key: 'Alrm_iAlarmIndex',
            description: '报警代码',
            lastKey: 'Alrm_iAlarmIndex'
        }, {
            key: 'strAlarmTime',
            description: '报警时间',
            lastKey: 'strAlarmTime'
        }, {
            key: 'iAlarmDetails',
            description: '报警内容',
            lastKey: 'iAlarmDetails'
        }, {
            key: 'TCP_iCurrentMode',
            description: '工作模式',
            lastKey: 'TCP_iCurrentMode'
        }, {
            key: 'TCP_iMotorStatus',
            description: '电机状态',
            lastKey: 'TCP_iMotorStatus'
        }, {
            key: 'STC_bUDiskValid',
            description: 'U盘状态',
            lastKey: 'STC_bUDiskValid'
        }, {
            key: 'TCP_strSysClockDate',
            description: '系统时间',
            lastKey: 'TCP_strSysClockDate'
        }, {
            key: 'PMP_rAtlPos',
            description: '电缸压头实时位置',
            lastKey: 'PMP_rAtlPos'
        }, {
            key: 'PMP_rAtlPre',
            description: '压力传感器实时压力值',
            lastKey: 'PMP_rAtlPre'
        }, {
            key: 'CYL_rActionTime',
            description: '当前动作运行时间',
            lastKey: 'CYL_rActionTime'
        }, {
            key: 'CYL_rCycleTime',
            description: '本周期进行时间',
            lastKey: 'CYL_rCycleTime'
        }, {
            key: 'MLD_strCurrentFile',
            description: '当前模具名称',
            lastKey: 'MLD_strCurrentFile'
        }, {
            key: 'TCP_iCurrentStage',
            description: '运动过程',
            lastKey: 'TCP_iCurrentStage'
        }, {
            key: 'PMP_iSetPushNum',
            description: '当前压装次数',
            lastKey: 'PMP_iSetPushNum'
        }, {
            key: 'QCM_bProductQualityOK',
            description: '本次是否合格',
            lastKey: 'QCM_bProductQualityOK'
        }, {
            key: 'strBarCode',
            description: '条形码',
            lastKey: 'strBarCode'
        }, {
            key: 'rActuallyContactPos',
            description: '接触位置',
            lastKey: 'rActuallyContactPos'
        }, {
            key: 'rAtlFinishPre',
            description: '终止压力',
            lastKey: 'rAtlFinishPre'
        }, {
            key: 'rAtlFinishPos',
            description: '终止位置',
            lastKey: 'rAtlFinishPos'
        }, {
            key: 'iActuallyPushmountingMode',
            description: '当前压装模式',
            lastKey: 'iActuallyPushmountingMode'
        }, {
            key: 'iParamsCheck1Mode',
            description: '质量判断1类型',
            lastKey: 'iParamsCheck1Mode'
        }, {
            key: 'rAtlParamsCheck1Val',
            description: '检测判断1检测值',
            lastKey: 'rAtlParamsCheck1Val'
        }, {
            key: 'rAtlParamsCheck1ValMax',
            description: '检测判断1最大值',
            lastKey: 'rAtlParamsCheck1ValMax'
        }, {
            key: 'rAtlParamsCheck1ValMin',
            description: '检测判断1最小值',
            lastKey: 'rAtlParamsCheck1ValMin'
        }, {
            key: 'iParamsCheck2Mode',
            description: '质量判断2类型',
            lastKey: 'iParamsCheck2Mode'
        }, {
            key: 'rAtlParamsCheck2Val',
            description: '检测判断2检测值',
            lastKey: 'rAtlParamsCheck2Val'
        }, {
            key: 'rAtlParamsCheck2ValMax',
            description: '检测判断2最大值',
            lastKey: 'rAtlParamsCheck2ValMax'
        }, {
            key: 'rAtlParamsCheck2ValMin',
            description: '检测判断2最小值',
            lastKey: 'rAtlParamsCheck2ValMin'
        }, {
            key: 'iParamsCheck3Mode',
            description: '质量判断3类型',
            lastKey: 'iParamsCheck3Mode'
        }, {
            key: 'rAtlParamsCheck3Val',
            description: '检测判断3检测值',
            lastKey: 'rAtlParamsCheck3Val'
        }, {
            key: 'rAtlParamsCheck3ValMax',
            description: '检测判断3最大值',
            lastKey: 'rAtlParamsCheck3ValMax'
        }, {
            key: 'rAtlParamsCheck3ValMin',
            description: '检测判断3最小值',
            lastKey: 'rAtlParamsCheck3ValMin'
        }, {
            key: 'iParamsCheck4Mode',
            description: '质量判断4类型',
            lastKey: 'iParamsCheck4Mode'
        }, {
            key: 'rAtlParamsCheck4Val',
            description: '检测判断4检测值',
            lastKey: 'rAtlParamsCheck4Val'
        }, {
            key: 'rAtlParamsCheck4ValMax',
            description: '检测判断4最大值',
            lastKey: 'rAtlParamsCheck4ValMax'
        }, {
            key: 'rAtlParamsCheck4ValMin',
            description: '检测判断4最小值',
            lastKey: 'rAtlParamsCheck4ValMin'
        }, {
            key: 'iParamsCheck5Mode',
            description: '质量判断5类型',
            lastKey: 'iParamsCheck5Mode'
        }, {
            key: 'rAtlParamsCheck5Val',
            description: '检测判断5检测值',
            lastKey: 'rAtlParamsCheck5Val'
        }, {
            key: 'rAtlParamsCheck5ValMax',
            description: '检测判断5最大值',
            lastKey: 'rAtlParamsCheck5ValMax'
        }, {
            key: 'rAtlParamsCheck5ValMin',
            description: '检测判断5最小值',
            lastKey: 'rAtlParamsCheck5ValMin'
        }, {
            key: 'rMaxPre',
            description: '最大压力',
            lastKey: 'rMaxPre'
        }, {
            key: 'rMaxPos',
            description: '最大位置',
            lastKey: 'rMaxPos'
        }, {
            key: 'PSM_diCurCntBad',
            description: '次品数',
            lastKey: 'PSM_diCurCntBad'
        }, {
            key: 'PSM_diCurProductSumCnt',
            description: '本次生产',
            lastKey: 'PSM_diCurProductSumCnt'
        }, {
            key: 'PSM_diProductSumCnt',
            description: '总生产数',
            lastKey: 'PSM_diProductSumCnt'
        }, {
            key: 'strProductTimer',
            description: '生产时间',
            lastKey: 'strProductTimer'
        }, {
            key: 'strProductQualityOK',
            description: '质量',
            lastKey: 'strProductQualityOK'
        }, {
            key: 'iPushOverNum',
            description: '当前压装次数',
            lastKey: 'iPushOverNum'
        }, {
            key: 'PSM_diSetBatchCnt',
            description: '计划产量',
            lastKey: 'PSM_diSetBatchCnt'
        }, {
            key: 'PSM_diAtlBatchCntBad',
            description: '批生产次品数',
            lastKey: 'PSM_diAtlBatchCntBad'
        }, {
            key: 'PSM_diAtlBatchCnt',
            description: '已生产数量',
            lastKey: 'PSM_diAtlBatchCnt'
        }, {
            key: 'bParamsEnable1',
            description: '检测启用标记',
            lastKey: 'bParamsEnable1'
        }, {
            key: 'bParamsEnable2',
            description: '检测启用标记',
            lastKey: 'bParamsEnable2'
        }, {
            key: 'bParamsEnable3',
            description: '检测启用标记',
            lastKey: 'bParamsEnable3'
        }, {
            key: 'bParamsEnable4',
            description: '检测启用标记',
            lastKey: 'bParamsEnable4'
        }, {
            key: 'bParamsEnable5',
            description: '检测启用标记',
            lastKey: 'bParamsEnable5'
        }, {
            key: 'rSetParamsCheckStartVal1',
            description: '开始值',
            lastKey: 'rSetParamsCheckStartVal1'
        }, {
            key: 'rSetParamsCheckStartVal2',
            description: '开始值',
            lastKey: 'rSetParamsCheckStartVal2'
        }, {
            key: 'rSetParamsCheckStartVal3',
            description: '开始值',
            lastKey: 'rSetParamsCheckStartVal3'
        }, {
            key: 'rSetParamsCheckStartVal4',
            description: '开始值',
            lastKey: 'rSetParamsCheckStartVal4'
        }, {
            key: 'rSetParamsCheckStartVal5',
            description: '开始值',
            lastKey: 'rSetParamsCheckStartVal5'
        }, {
            key: 'rSetParamsCheckStartVal',
            description: '开始值',
            lastKey: 'rSetParamsCheckStartVal'
        }, {
            key: 'rSetParamsCheckStopVal',
            description: '结束值',
            lastKey: 'rSetParamsCheckStopVal'
        }, {
            key: 'rSetParamsCheckStopVal1',
            description: '结束值',
            lastKey: 'rSetParamsCheckStopVal1'
        }, {
            key: 'rSetParamsCheckStopVal2',
            description: '结束值',
            lastKey: 'rSetParamsCheckStopVal2'
        }, {
            key: 'rSetParamsCheckStopVal3',
            description: '结束值',
            lastKey: 'rSetParamsCheckStopVal3'
        }, {
            key: 'rSetParamsCheckStopVal4',
            description: '结束值',
            lastKey: 'rSetParamsCheckStopVal4'
        }, {
            key: 'rSetParamsCheckStopVal5',
            description: '结束值',
            lastKey: 'rSetParamsCheckStopVal5'
        }, {
            key: 'bJudgtEnable',
            description: '检测是否启用',
            lastKey: 'bJudgtEnable'
        }, {
            key: 'iCurrentPushNumForQCM',
            description: '当前压装的次数',
            lastKey: 'iCurrentPushNumForQCM'
        }
            /* ,{
                key: 'iSetEnterSide',
                description: '检测信号进入侧参数',
                lastKey: 'iSetEnterSide'
            }, {
                key: 'iSetLeaveSide',
                description: '检测信号离开侧参数',
                lastKey: 'iSetLeaveSide'
            }*/
        ]
    };
    return settingConfig;
});