define([], function () {
    let settingConfig = {
        app: 'welding_device',
        dialogTitle: '弧焊机器人数据配置',
        fields: [{"key": "001_CloudVersion", "description": "Cloud数据协议版本号"},
            {"key": "002_DataType", "description": "静态数据or动态数据"},
            {"key": "004_UserName", "description": "用户名"},
            {"key": "005_IPAddress1", "description": "IP地址1"},
            {"key": "006_IPAddress2", "description": "IP地址2"},
            {"key": "007_MACAddress1", "description": "Mac address 1地址"},
            {"key": "008_MACAddress2", "description": "Mac address 2地址"},
            {"key": "009_UserCodeDefault", "description": "User code前三段"},
            {"key": "010_UserCodeAddtion", "description": "User code后一段"},
            {"key": "011_MachineCode", "description": "机器码"},
            {"key": "012_FactoryName", "description": "工厂名字"},
            {"key": "013_LineName", "description": "生产线名字"},
            {"key": "014_LocationName", "description": "工位名字"},
            {"key": "021_ControllerVersion", "description": "控制器版本"},
            {"key": "022_CPACVersion", "description": "CPAC版本"},
            {"key": "023_RobotConrolSystemVersion", "description": "机器人控制系统版本"},
            {"key": "024_TaskLibVersion", "description": "task库版本"},
            {"key": "025_MotionLibVersion", "description": "motion库版本"},
            {"key": "026_HMILibVersion", "description": "Hmi库版本"},
            {"key": "027_MotionAdditionLibVersion", "description": "MotionAddition库版本"},
            {"key": "028_PalletEasyVersion", "description": "Pallet Easy库版本"},
            {"key": "029_TCPIPLibVersion", "description": "TCPIP库版本"},
            {"key": "041_PalletizeAppSupport", "description": "码垛工艺是否激活"},
            {"key": "042_WeldingAppSupport", "description": "焊接工艺是否激活"},
            {"key": "043_TrackingAppSupport", "description": "跟踪工艺是否激活"},
            {"key": "044_ExtAxesAppSupport", "description": "外部轴工艺是否激活"},
            {"key": "045_VisionAppSupport", "description": "视觉工艺是否激活"},
            {"key": "046_LaserAppSupport", "description": "激光切割工艺是否激活"},
            {"key": "047_CNCAppSupport", "description": "CNC工艺是否激活"},
            {"key": "048_BendAppSupport", "description": "折弯工艺是否激活"},
            {"key": "049_CalibrationAppSupport", "description": "标定工艺是否激活"},
            {"key": "050_JASICAppSupport", "description": "佳士定制工艺是否激活"},
            {"key": "051_DynDirectTeachAppSupport", "description": "拖动示教工艺是否激活"},
            {"key": "052_DynCollisionDetectedAppSupport", "description": "碰撞检测工艺是否激活"},
            {"key": "053_DynFeedForwardAppSupport", "description": "动力学前馈工艺是否激活"},
            {"key": "061_RobotType", "description": "机器人模型类型"},
            {"key": "062_ControllerType", "description": "控制器硬件类型"},
            {"key": "063_InterpolationCycleTime", "description": "插补时间"},
            {"key": "064_AxisNumber", "description": "轴数量"},
            {"key": "065_EncoderType", "description": "编码器类型"},
            {"key": "071_Axis1ReferencePosition", "description": "Axis1 零点位置"},
            {"key": "072_Axis2ReferencePosition", "description": "Axis2 零点位置"},
            {"key": "073_Axis3ReferencePosition", "description": "Axis3 零点位置"},
            {"key": "074_Axis4ReferencePosition", "description": "Axis4 零点位置"},
            {"key": "075_Axis5ReferencePosition", "description": "Axis5 零点位置"},
            {"key": "076_Axis6ReferencePosition", "description": "Axis6 零点位置"},
            {"key": "077_Axis7ReferencePosition", "description": "Axis7 零点位置"},
            {"key": "078_Axis8ReferencePosition", "description": "Axis8 零点位置"},
            {"key": "003_Axis1ProfilePosition", "description": "Axis1规划位置"},
            {"key": "004_Axis2ProfilePosition", "description": "Axis2规划位置"},
            {"key": "005_Axis3ProfilePosition", "description": "Axis3规划位置"},
            {"key": "006_Axis4ProfilePosition", "description": "Axis4规划位置"},
            {"key": "007_Axis5ProfilePosition", "description": "Axis5规划位置"},
            {"key": "008_Axis6ProfilePosition", "description": "Axis6规划位置"},
            {"key": "009_Axis7ProfilePosition", "description": "Axis7规划位置"},
            {"key": "010_Axis8ProfilePosition", "description": "Axis8规划位置"},
            {"key": "011_CartesianXPosition", "description": "笛卡尔坐标系位置X"},
            {"key": "012_CartesianYPosition", "description": "笛卡尔坐标系位置Y"},
            {"key": "013_CartesianZPosition", "description": "笛卡尔坐标系位置Z"},
            {"key": "014_CartesianAPosition", "description": "笛卡尔坐标系位置A"},
            {"key": "015_CartesianBPosition", "description": "笛卡尔坐标系位置B"},
            {"key": "016_CartesianCPosition", "description": "笛卡尔坐标系位置C"},
            {"key": "019_Axis1ProfileVelocity", "description": "Axis1 规划速度"},
            {"key": "020_Axis2ProfileVelocity", "description": "Axis2 规划速度"},
            {"key": "021_Axis3ProfileVelocity", "description": "Axis3 规划速度"},
            {"key": "022_Axis4ProfileVelocity", "description": "Axis4 规划速度"},
            {"key": "023_Axis5ProfileVelocity", "description": "Axis5 规划速度"},
            {"key": "024_Axis6ProfileVelocity", "description": "Axis6 规划速度"},
            {"key": "025_Axis7ProfileVelocity", "description": "Axis7 规划速度"},
            {"key": "026_Axis8ProfileVelocity", "description": "Axis8 规划速度"},
            {"key": "027_Motor1Speed", "description": "Motor1转速"},
            {"key": "028_Motor2Speed", "description": "Motor2转速"},
            {"key": "029_Motor3Speed", "description": "Motor3转速"},
            {"key": "030_Motor4Speed", "description": "Motor4转速"},
            {"key": "031_Motor5Speed", "description": "Motor5转速"},
            {"key": "032_Motor6Speed", "description": "Motor6转速"},
            {"key": "033_Motor7Speed", "description": "Motor7转速"},
            {"key": "034_Motor8Speed", "description": "Motor8转速"},
            {"key": "035_Axis1TheoryDynamicsCurrent", "description": "Axis1理论电流"},
            {"key": "036_Axis2TheoryDynamicsCurrent", "description": "Axis2理论电流"},
            {"key": "037_Axis3TheoryDynamicsCurrent", "description": "Axis3理论电流"},
            {"key": "038_Axis4TheoryDynamicsCurrent", "description": "Axis4理论电流"},
            {"key": "039_Axis5TheoryDynamicsCurrent", "description": "Axis5理论电流"},
            {"key": "040_Axis6TheoryDynamicsCurrent", "description": "Axis6理论电流"},
            {"key": "041_Axis7TheoryDynamicsCurrent", "description": "Axis7理论电流"},
            {"key": "042_Axis8TheoryDynamicsCurrent", "description": "Axis8理论电流"},
            {"key": "043_Axis1ActualCurrent", "description": "Axis1实际电流"},
            {"key": "044_Axis2ActualCurrent", "description": "Axis2实际电流"},
            {"key": "045_Axis3ActualCurrent", "description": "Axis3实际电流"},
            {"key": "046_Axis4ActualCurrent", "description": "Axis4实际电流"},
            {"key": "047_Axis5ActualCurrent", "description": "Axis5实际电流"},
            {"key": "048_Axis6ActualCurrent", "description": "Axis6实际电流"},
            {"key": "049_Axis7ActualCurrent", "description": "Axis7实际电流"},
            {"key": "050_Axis8ActualCurrent", "description": "Axis8实际电流"},
            {"key": "051_Axis1Collision", "description": "Axis1 碰撞信号"},
            {"key": "052_Axis2Collision", "description": "Axis2 碰撞信号"},
            {"key": "053_Axis3Collision", "description": "Axis3 碰撞信号"},
            {"key": "054_Axis4Collision", "description": "Axis4 碰撞信号"},
            {"key": "055_Axis5Collision", "description": "Axis5 碰撞信号"},
            {"key": "056_Axis6Collision", "description": "Axis6 碰撞信号"},
            {"key": "059_WorkMode", "description": "工作模式"},
            {"key": "060_ServoOnStatus", "description": "使能状态：1或者0"},
            {"key": "061_VisuPage", "description": "当前页面"},
            {"key": "062_JOG_Axis", "description": "JOG轴号"},
            {"key": "063_JOG_Direction", "description": "JOG方向"},
            {"key": "064_JOG_Coordsys", "description": "JOG坐标系"},
            {"key": "065_JOG_VEL", "description": "JOG速度"},
            {"key": "066_TeachFileName", "description": "当前示教文件名称"},
            {"key": "067_TeachFileLine", "description": "当前示教文件行号"},
            {"key": "068_ERRORStatus", "description": "错误状态"},
            {"key": "069_ERRORCode", "description": "错误码"},
            {"key": "070_TCSNumber", "description": "当前工具坐标系"},
            {"key": "071_WCSNumber", "description": "当前世界坐标系"},
            {"key": "072_PCS1Number", "description": "工件坐标系1"},
            {"key": "073_PCS2Number", "description": "工件坐标系2"},
            {"key": "074_Exit3key", "description": "3键退出系统标识"},
            {"key": "075_CollisionFlag", "description": "整体碰撞标识"},
            {"key": "076_LineVelocity", "description": "线性速度"},
            {"key": "077_Axis1ProfileAcc", "description": "轴1规划加速度"},
            {"key": "078_Axis2ProfileAcc", "description": "轴2规划加速度"},
            {"key": "079_Axis3ProfileAcc", "description": "轴3规划加速度"},
            {"key": "080_Axis4ProfileAcc", "description": "轴4规划加速度"},
            {"key": "081_Axis5ProfileAcc", "description": "轴5规划加速度"},
            {"key": "082_Axis6ProfileAcc", "description": "轴6规划加速度"},
            {"key": "083_Axis7ProfileAcc", "description": "轴7规划加速度"},
            {"key": "084_Axis8ProfileAcc", "description": "轴8规划加速度"},
            {"key": "085_OrientationNumber", "description": "姿态代号"},
            {"key": "086_BootTime", "description": "开机时间"},
            {"key": "087_RunTime", "description": "运行时间"},
            {"key": "101_Status_DI_ArcWeldingStart", "description": "引弧成功"},
            {"key": "102_Status_DI_WelderOK", "description": "焊机正常信号"},
            {"key": "103_Status_DI_GasNotEnough", "description": "保护气不足"},
            {"key": "104_Status_DI_WireNotEnough", "description": "焊丝不足"},
            {"key": "105_Status_DI_WireStick", "description": "粘丝检测输入"},
            {"key": "106_Status_DI_SearchPosIn", "description": "寻位输入"},
            {"key": "107_Status_DI_CoolingSys", "description": "冷却系统"},
            {"key": "108_Status_DI_ExGasCheck", "description": "外部检气"},
            {"key": "109_Status_DI_ExWireFw", "description": "外部进丝"},
            {"key": "110_Status_DI_ExWireBw", "description": "外部退丝"},
            {"key": "111_Status_DI_ExArcWeldingOn", "description": "外部焊接开关"},
            {"key": "112_Status_DO_ArcOn", "description": "引弧"},
            {"key": "113_Status_DO_GasCheck", "description": "检气"},
            {"key": "114_Status_DO_WireFw", "description": "进丝"},
            {"key": "115_Status_DO_WireBw", "description": "退丝"},
            {"key": "116_Status_DO_SearchPosOut", "description": "寻位输出"},
            {"key": "117_Status_DO_WireStick", "description": "粘丝检测输出"},
            {"key": "118_Par_WeldingCurrent", "description": "给定电流"},
            {"key": "119_Par_WeldingVoltage", "description": "给定电压"},
            {"key": "120_Status_WeldingCurrent", "description": "反馈电流"},
            {"key": "121_Status_WeldingVoltage", "description": "反馈电压"},
            {"key": "122_Status_ArcTrackHorUse", "description": "左右跟踪开关"},
            {"key": "123_Status_ArcTrackHorSingle", "description": "左右单周期补偿量"},
            {"key": "124_Status_ArcTrackHorSum", "description": "左右总补偿量"},
            {"key": "125_Status_ArcTrackVerUse", "description": "上下跟踪开关"},
            {"key": "126_Status_ArcTrackVerSingle", "description": "上下单周期补偿量"},
            {"key": "127_Status_ArcTrackVerSum", "description": "上下总补偿量"},
            {"key": "128_Par_WelderType", "description": "焊机类型"},
            {"key": "129_Par_FileIndex", "description": "焊接参数序号"},
            {"key": "130_Par_MaterialType", "description": "焊材类型"},
            {"key": "131_Par_WireType", "description": "焊丝类型"},
            {"key": "132_Par_GasType", "description": "保护气类型"},
            {"key": "141_ArcOn_Time", "description": "起弧成功时间"}
        ]
    };
    return settingConfig;
});